version: '3'

# docker-compose up --build -d
# docker-compose down

# service contient des containers 
services:

  db:
    image: mysql:5.6

    environment :
      MYSQL_ROOT_PASSWORD : 'root'

    volumes : 
      - ./db2:/var/lib/mysql
  myapp:

   # image: myapp
   build : . 

   volumes:
    #
     - ./src/upload:/var/www/html/upload   

   ports:  
    - 5000:80

   